<?php

/**
 * This is the model base class for the table "comentario".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Comentario".
 *
 * Columns in table "comentario" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id_comentario
 * @property integer $id_post
 * @property integer $id_usuario
 * @property string $texto
 * @property string $data
 *
 */
abstract class BaseComentario extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'comentario';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Comentario|Comentarios', $n);
	}

	public static function representingColumn() {
		return 'data';
	}

	public function rules() {
		return array(
			array('id_post, id_usuario, data, texto', 'required'),
			array('id_post, id_usuario', 'numerical', 'integerOnly'=>true),
			array('texto', 'length', 'max'=>255),
			array('texto', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_comentario, id_post, id_usuario, texto, data', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'post' => array(self::BELONGS_TO, 'Post', 'id_post'),
			'usuario' => array(self::BELONGS_TO, 'Usuario', 'id_usuario'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_comentario' => Yii::t('app', 'Id Comentario'),
			'id_post' => null,
			'id_usuario' => null,
			'texto' => Yii::t('app', 'Texto'),
			'data' => Yii::t('app', 'Data'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_comentario', $this->id_comentario);
		$criteria->compare('id_post', $this->id_post);
		$criteria->compare('id_usuario', $this->id_usuario);
		$criteria->compare('texto', $this->texto, true);
		$criteria->compare('data', $this->data, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}