-- MySQL Script generated by MySQL Workbench
-- Wed Aug  3 08:30:23 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


-- -----------------------------------------------------
-- Schema db_blogconexa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_blogconexa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_blogconexa` DEFAULT CHARACTER SET utf8 ;
USE `db_blogconexa` ;

-- -----------------------------------------------------
-- Table `db_blogconexa`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_blogconexa`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(60) NOT NULL,
  `coworking` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_blogconexa`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_blogconexa`.`categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_categoria`),
  UNIQUE INDEX `id_categoria_UNIQUE` (`id_categoria` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_blogconexa`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_blogconexa`.`post` (
  `id_post` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_categoria` INT NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `texto` LONGTEXT NOT NULL,
  `data` DATE NOT NULL,
  PRIMARY KEY (`id_post`),
  UNIQUE INDEX `id_post_UNIQUE` (`id_post` ASC),
  INDEX `FK_USUARIO_idx` (`id_usuario` ASC),
  INDEX `FK_CATEGORIA_idx` (`id_categoria` ASC),
  CONSTRAINT `FK_POST_USUARIO`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db_blogconexa`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_POST_CATEGORIA`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `db_blogconexa`.`categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_blogconexa`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_blogconexa`.`comentario` (
  `id_comentario` INT NOT NULL AUTO_INCREMENT,
  `id_post` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `texto` VARCHAR(255) NOT NULL,
  `data` DATE NOT NULL,
  PRIMARY KEY (`id_comentario`),
  UNIQUE INDEX `id_comentario_UNIQUE` (`id_comentario` ASC),
  INDEX `FK_COMENTARIO_POST_idx` (`id_post` ASC),
  INDEX `FK_COMENTARIO_USUARIO_idx` (`id_usuario` ASC),
  CONSTRAINT `FK_COMENTARIO_POST`
    FOREIGN KEY (`id_post`)
    REFERENCES `db_blogconexa`.`post` (`id_post`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_COMENTARIO_USUARIO`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db_blogconexa`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `categoria` VALUES (null,'Integrações');
INSERT INTO `categoria` VALUES (null,'Serviços');
INSERT INTO `categoria` VALUES (null,'Financeiro');
INSERT INTO `categoria` VALUES (null,'Agenda');
INSERT INTO `categoria` VALUES (null,'Parceiros');
INSERT INTO `categoria` VALUES (null,'Outros');
